name: subwhisper
channels:
  - pytorch
  - nvidia  # for optional CUDA packages
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg  # optional; alternatively install via system package manager
  - pip
  # Uncomment the following line to match your CUDA toolkit version
  # - pytorch-cuda=11.8  # requires NVIDIA channel
  - pip:
      - ctranslate2>=4.4  # requires version without pkg_resources
      - torch==1.13.1  # required for pretrained Pyannote models
      - pyannote.audio>=2.1,<3  # required for 'pyannote/vad'
      - speechbrain>=1.0
      - whisperx>=3.4.2,<4
      - librosa>=0.10
      - noisereduce>=3.0
      - packaging        # version parsing for dependency checks
      # Optional extras
      - rich             # pretty logging in the terminal
      - pyyaml
      - language_tool_python
      - jiwer>=3.0
      - aeneas>=1.7.3
      - fastapi
      - uvicorn
      - pysubs2>=1.8.0  # subtitle parsing support
