name: subwhisper
channels:
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg
  - pip
  - pip:
      - ctranslate2>=4.4,<5
      - faster-whisper>=1.2,<2
      - numpy>=1.26,<3
      - librosa>=0.10
      - noisereduce>=3.0
      - soundfile>=0.12
      - packaging
      - rich
      - pyyaml
      - language_tool_python
      - jiwer>=3.0
      - aeneas>=1.7.3
      - fastapi
      - uvicorn
      - pysubs2>=1.8.0
