name: subwhisper
channels:
  - pytorch
  - nvidia  # for optional CUDA packages
  - conda-forge
dependencies:
  - python=3.10
  - ffmpeg  # optional; alternatively install via system package manager
  - pip
  # Uncomment the following line to match your CUDA toolkit version
  # - pytorch-cuda=11.8  # requires NVIDIA channel
  - pip:
      - ctranslate2>=4.3  # use version without pkg_resources
      - torch>=2.5
      - pyannote.audio>=3.3
      - speechbrain>=1.0
      - whisperx>=3.4.2,<4
      - librosa>=0.10
      - packaging        # version parsing for dependency checks
      # Optional extras
      - rich             # pretty logging in the terminal
